services:

  apache4:
    image: "apache4:v3.5"
    container_name: "apache4"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "apache4/whoami"
    container_name: "simple-service"
    labels:
      - "apache4.enable=true"
      - "apache4.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "apache4.http.routers.whoami.entrypoints=web"
