blank_issues_enabled: false
contact_links:
  - name: apache4 Community Support
    url: https://community.apache4.io/
    about: If you have a question, or are looking for advice, please post on our Discuss forum! The community loves to chime in to help. Happy Coding!
  - name: apache4 Helm Chart Issues
    url: https://github.com/apache4/apache4-helm-chart
    about: Are you submitting an issue or feature enhancement for the apache4 helm chart? Please post in the apache4-helm-chart GitHub Issues.
