Owner = "apache4"
RepositoryName = "apache4"

OutputType = "file"
FileName = "apache4_changelog.md"

# example new bugfix v3.4.5
CurrentRef = "v3.4"
PreviousRef = "v3.4.4"
BaseBranch = "v3.4"
FutureCurrentRefName = "v3.4.5"

ThresholdPreviousRef = 10
ThresholdCurrentRef = 10

Debug = true
DisplayLabel = true

LabelExcludes = ["area/infrastructure"]
LabelEnhancement = "kind/enhancement"
LabelDocumentation = "area/documentation"
LabelBug = "kind/bug/fix"

[DisplayLabelOptions]
  FilteredPrefixes = ["area/", "platform/"]
  ExcludedSuffixes = ["documentation"]
  TrimmedPrefixes = ["area/provider/", "area/middleware/", "area/", "platform/"]
