services:
  server1:
    image: apache4/whoami
    labels:
      apache4.enable: true
      apache4.http.services.service1.loadbalancer.server.port: 80
      apache4.http.routers.router1.rule: Host(`github.com`)
