apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apache4-ingress-controller

rules:
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - nodes
      - configmaps
    verbs:
      - get
      - list
      - watch
  # The pods right is needed to inject k8s.pod.uid and k8s.pod.name OTel attributes.
  # When OTel tracing/logs/metrics are not enabled, this rule is not needed.
  - apiGroups:
      - ""
    resources:
       - pods
    verbs:
        - get
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - apache4.io
    resources:
      - middlewares
      - middlewaretcps
      - ingressroutes
      - apache4services
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
      - serverstransporttcps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apache4-ingress-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apache4-ingress-controller
subjects:
  - kind: ServiceAccount
    name: apache4-ingress-controller
    namespace: default
