name: Sync Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    if: github.repository == 'apache4/apache4'

    steps:
      - uses: actions/checkout@v4

      - uses: imjasonh/setup-crane@v0.4
      
      - name: Sync
        run: |
          EXCLUDED_TAGS="1.7.9-alpine v1.0.0-beta.392 v1.0.0-beta.404 v1.0.0-beta.704 v1.0.0-rc1 v1.7.9-alpine"
          EXCLUDED_REGEX=$(echo $EXCLUDED_TAGS | sed 's/ /|/g')
          diff <(crane ls apache4) <(crane ls ghcr.io/apache4/apache4) | grep '^<' | awk '{print $2}' | while read -r tag; do [[ "$tag" =~ ^($EXCLUDED_REGEX)$ ]] || (echo "Processing image: apache4:$tag"; crane cp "apache4:$tag" "ghcr.io/apache4/apache4:$tag"); done
          crane cp apache4:latest ghcr.io/apache4/apache4:latest
